version: '3.7'

services:
  postgres:
    container_name: askmeDB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=askme
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:14.5-alpine
